# Setup
title:               My blog
tagline:             'Static website made with jekyll'
description:         'A static website made with jekyll, hosted by Github Pages for KMU Eureka Project 2022-2nd term'
url:                 https://20223073.github.io
baseurl:             ''
paginate:            6
permalink:           pretty

# About/contact
author:
  name:              20223073
  url:               https://20223073.github.io
  email:             20223073@kookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
excerpt_separator:   <!--more-->
comment:
  provider:          "disqus"
  disqus:
    shortname:       "20223073"
    
 # Google Analytics
google_analytics:    G-Q3D9EFD2ZP
